#!/bin/bash

rm -rf /home/zlq/bianyi/lede/package/OpenAppFilter
rm -rf /home/zlq/bianyi/lede/package/luci-app-jd-dailybonus
rm -rf /home/zlq/bianyi/lede/package/luci-app-ttnode
rm -rf /home/zlq/bianyi/lede/package/lua-maxminddb
rm -rf /home/zlq/bianyi/lede/package/luci-app-vssr
rm -rf /home/zlq/bianyi/lede/package/luci-app-adguardhome
rm -rf /home/zlq/bianyi/lede/package/luci-app-dockerman
rm -rf /home/zlq/bianyi/lede/package/luci-app-autoipsetadder
rm -rf /home/zlq/bianyi/lede/package/openwrt-dogcom
rm -rf /home/zlq/bianyi/lede/package/luci-app-bypass
rm -rf /home/zlq/bianyi/lede/package/luci-app-openclash
rm -rf /home/zlq/bianyi/lede/package/brook
rm -rf /home/zlq/bianyi/lede/package/chinadns-ng
rm -rf /home/zlq/bianyi/lede/package/tcping
rm -rf /home/zlq/bianyi/lede/package/trojan-go
rm -rf /home/zlq/bianyi/lede/package/trojan-plus
rm -rf /home/zlq/bianyi/lede/package/luci-app-filebrowser
rm -rf /home/zlq/bianyi/lede/package/filebrowser
rm -rf /home/zlq/bianyi/lede/package/luci-app-fileassistant
rm -rf /home/zlq/bianyi/lede/package/luci-app-passwall
rm -rf /home/zlq/bianyi/lede/package/ssocks
rm -rf /home/zlq/bianyi/lede/package/xray-core
rm -rf /home/zlq/bianyi/lede/package/xray-plugin
rm -rf /home/zlq/bianyi/lede/package/shadowsocks-rust
rm -rf /home/zlq/bianyi/lede/package/v2ray-plugin
rm -rf /home/zlq/bianyi/lede/package/shadowsocksr-libev
rm -rf /home/zlq/bianyi/lede/package/luci-app-gost
rm -rf /home/zlq/bianyi/lede/package/gost
rm -rf /home/zlq/bianyi/lede/package/luci-app-eqos
rm -rf /home/zlq/bianyi/lede/package/luci-app-serverchan
rm -rf /home/zlq/bianyi/lede/package/wrtbwmon
rm -rf /home/zlq/bianyi/lede/luci-app-wrtbwmon
rm -rf /home/zlq/bianyi/lede/package/luci-app-wrtbwmon
rm -rf /home/zlq/bianyi/lede/package/luci-theme-Butterfly
rm -rf /home/zlq/bianyi/lede/package/luci-theme-Butterfly-dark
rm -rf /home/zlq/bianyi/lede/package/luci-theme-darkmatter
rm -rf /home/zlq/bianyi/lede/package/luci-theme-opentomato
rm -rf /home/zlq/bianyi/lede/package/luci-theme-edge
rm -rf /home/zlq/bianyi/lede/package/luci-theme-argon
rm -rf /home/zlq/bianyi/lede/package/luci-app-argon-config
rm -rf /home/zlq/bianyi/lede/package/luci-theme-rosy
rm -rf /home/zlq/bianyi/lede/package/luci-theme-purple
rm -rf /home/zlq/bianyi/lede/package/luci-theme-infinityfreedom
rm -rf /home/zlq/bianyi/lede/package/luci-theme-opentomcat
rm -rf /home/zlq/bianyi/lede/package/luci-theme-atmaterial
rm -rf /home/zlq/bianyi/lede/package/luci-theme-opentopd
rm -rf /home/zlq/bianyi/lede/package/luci-app-socat
rm -rf /home/zlq/bianyi/lede/package/luci-app-koolddns
rm -rf /home/zlq/bianyi/lede/package/luci-app-ssr-plus
rm -rf /home/zlq/bianyi/lede/package/naiveproxy
rm -rf /home/zlq/bianyi/lede/package/luci-app-unblockneteasemusic-mini
rm -rf /home/zlq/bianyi/lede/package/quickjspp
rm -rf /home/zlq/bianyi/lede/package/jpcre2
rm -rf /home/zlq/bianyi/lede/package/libcron
rm -rf /home/zlq/bianyi/lede/package/rapidjson
rm -rf /home/zlq/bianyi/lede/package/subconverter
rm -rf /home/zlq/bianyi/lede/package/smartdns-le
rm -rf /home/zlq/bianyi/lede/package/luci-app-smartdns
rm -rf /home/zlq/bianyi/lede/package/ddnsto
rm -rf /home/zlq/bianyi/lede/package/luci-app-ddnsto
rm -rf /home/zlq/bianyi/lede/package/openwrt-udp2raw
rm -rf /home/zlq/bianyi/lede/package/luci-app-udp2raw
